# Generated by Django 4.1.2 on 2022-10-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_job_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_master',
        ),
    ]
