# Generated by Django 4.1.2 on 2022-10-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_job_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('c_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='home.client_master')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='home.client_master')),
            ],
        ),
    ]
