# Generated by Django 4.1.2 on 2022-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_job_master_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_master',
            name='Inspector',
        ),
        migrations.AddField(
            model_name='job_master',
            name='insp_master',
            field=models.ManyToManyField(to='home.inspector_master'),
        ),
    ]
