# Generated by Django 4.1.2 on 2022-10-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_job_master_inspector_job_master_insp_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_master',
        ),
    ]
