# Generated by Django 4.1.2 on 2022-10-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_job_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspector_master',
            old_name='full_name',
            new_name='insp_master_full_name',
        ),
        migrations.RenameField(
            model_name='job_master',
            old_name='full_name',
            new_name='insp_master_full_name',
        ),
    ]
