# Generated by Django 4.1.2 on 2022-10-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_full_name_inspector_master_insp_master_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='full_name',
            new_name='manager_full_name',
        ),
        migrations.DeleteModel(
            name='job_master',
        ),
    ]
