# Generated by Django 4.1.2 on 2022-10-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_full_name_manager_manager_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_name', to='home.client_master')),
                ('insp_master_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insp_master', to='home.inspector_master')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_location', to='home.client_master')),
            ],
        ),
    ]
