# Generated by Django 4.1.2 on 2022-10-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_client_master_sl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_master',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='job_master',
            name='insp_master_full_name',
        ),
        migrations.RemoveField(
            model_name='job_master',
            name='location',
        ),
        migrations.DeleteModel(
            name='client_master',
        ),
        migrations.DeleteModel(
            name='inspector_master',
        ),
        migrations.DeleteModel(
            name='job_master',
        ),
    ]
