# Generated by Django 4.1.2 on 2022-10-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client_master',
            new_name='co_client_master',
        ),
        migrations.RenameModel(
            old_name='inspector_master',
            new_name='co_inspector_master',
        ),
        migrations.RenameModel(
            old_name='job_master',
            new_name='co_job_master',
        ),
    ]
