# Generated by Django 4.1.2 on 2022-10-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator_admin', '0002_rename_client_master_co_client_master_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='co_client_master',
            new_name='client_master',
        ),
        migrations.RenameModel(
            old_name='co_inspector_master',
            new_name='inspector_master',
        ),
        migrations.RenameModel(
            old_name='co_job_master',
            new_name='job_master',
        ),
    ]
